package com.ollieread.technomagi;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Arrays;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.potion.Potion;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.ollieread.technomagi.common.CommonProxy;
import com.ollieread.technomagi.common.Information;
import com.ollieread.technomagi.common.Reference;
import com.ollieread.technomagi.common.init.Abilities;
import com.ollieread.technomagi.common.init.Blocks;
import com.ollieread.technomagi.common.init.Entities;
import com.ollieread.technomagi.common.init.Items;
import com.ollieread.technomagi.common.init.Knowledge;
import com.ollieread.technomagi.common.init.Potions;
import com.ollieread.technomagi.common.init.Specialisations;
import com.ollieread.technomagi.creativetab.CreativeTabTM;
import com.ollieread.technomagi.network.PacketHandler;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;

@Mod(modid = Reference.MODID, version = Reference.VERSION, dependencies = "required-after:EnndsCore")
public class TechnoMagi
{

    @SidedProxy(clientSide = "com.ollieread.technomagi.client.ClientProxy", serverSide = "com.ollieread.technomagi.common.CommonProxy")
    public static CommonProxy proxy;

    @Instance(Reference.MODID)
    public static TechnoMagi instance;

    @Mod.Metadata(Reference.MODID)
    private static ModMetadata metadata;

    public static CreativeTabs tabTM = new CreativeTabTM();

    public static final Logger logger = LogManager.getLogger(Reference.MODID);

    @EventHandler
    public void pre(FMLPreInitializationEvent event)
    {
        metadata.modId = Reference.MODID;
        metadata.name = Reference.MODID;
        metadata.description = "A technology mod where the technology is so advanced, it gives the illusion of magic";
        metadata.url = "http://technomagi.ollieread.com/";
        metadata.logoFile = "assets/technomagi/logo.png";
        metadata.version = Reference.VERSION;
        metadata.authorList = Arrays.asList(new String[] { "ollieread" });
        metadata.credits = "AbrarSyed, for he promised that gradle will never touch your sources. ever.";
        metadata.autogenerated = false;

        proxy.registerEventHandlers();

        PacketHandler.init();
        Specialisations.init();
        Knowledge.init();
        Abilities.init();

        Entities.init();

        Blocks.init();
        Items.init();

        Potion[] potionTypes = null;

        for (Field f : Potion.class.getDeclaredFields()) {
            f.setAccessible(true);

            try {
                if (f.getName().equals("potionTypes") || f.getName().equals("field_76425_a")) {
                    Field modfield = Field.class.getDeclaredField("modifiers");
                    modfield.setAccessible(true);
                    modfield.setInt(f, f.getModifiers() & ~Modifier.FINAL);

                    potionTypes = (Potion[]) f.get(null);
                    final Potion[] newPotionType = new Potion[256];
                    System.arraycopy(potionTypes, 0, newPotionType, 0, potionTypes.length);
                    f.set(null, newPotionType);
                }
            } catch (Exception e) {
                System.err.println("Severe error, please report this to the mod author");
                System.err.println(e);
            }
        }

        Potions.init();
    }

    @EventHandler
    public void init(FMLInitializationEvent event)
    {
        proxy.init();

        NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
    }

    @EventHandler
    public void post(FMLPostInitializationEvent event)
    {
        Information.load("specialisations");
    }

}
