package com.ollieread.technomagi.common.init;

import net.minecraft.block.Block;

import com.ollieread.technomagi.TechnoMagi;
import com.ollieread.technomagi.block.BlockAirLight;
import com.ollieread.technomagi.block.BlockBattery;
import com.ollieread.technomagi.block.BlockDarkness;
import com.ollieread.technomagi.block.BlockDisplacedAir;
import com.ollieread.technomagi.block.BlockFiller;
import com.ollieread.technomagi.block.BlockGenerator;
import com.ollieread.technomagi.block.BlockHardlight;
import com.ollieread.technomagi.block.BlockHardlightFence;
import com.ollieread.technomagi.block.BlockHardlightGenerator;
import com.ollieread.technomagi.block.BlockLight;
import com.ollieread.technomagi.block.BlockMachine;
import com.ollieread.technomagi.block.BlockMachineInfuserCharger;
import com.ollieread.technomagi.block.BlockObservationChamber;
import com.ollieread.technomagi.block.BlockPocket;
import com.ollieread.technomagi.block.BlockPrismaticPillar;
import com.ollieread.technomagi.block.BlockReactiveCrafting;
import com.ollieread.technomagi.block.BlockRegionController;
import com.ollieread.technomagi.block.BlockResource;
import com.ollieread.technomagi.block.BlockSmartmetal;
import com.ollieread.technomagi.block.BlockSmartmetalTile;
import com.ollieread.technomagi.block.BlockStorage;
import com.ollieread.technomagi.block.BlockTank;
import com.ollieread.technomagi.block.BlockTeleporter;
import com.ollieread.technomagi.block.BlockVoidBreach;
import com.ollieread.technomagi.item.ItemBlockMulti;
import com.ollieread.technomagi.tileentity.TileEntityAirDisplaced;
import com.ollieread.technomagi.tileentity.TileEntityAirLight;
import com.ollieread.technomagi.tileentity.TileEntityAirVoidBreach;
import com.ollieread.technomagi.tileentity.TileEntityArchive;
import com.ollieread.technomagi.tileentity.TileEntityBattery;
import com.ollieread.technomagi.tileentity.TileEntityConstruct;
import com.ollieread.technomagi.tileentity.TileEntityFiller;
import com.ollieread.technomagi.tileentity.TileEntityGeneratorLife;
import com.ollieread.technomagi.tileentity.TileEntityGeneratorLight;
import com.ollieread.technomagi.tileentity.TileEntityGeneratorVoid;
import com.ollieread.technomagi.tileentity.TileEntityHardlightGenerator;
import com.ollieread.technomagi.tileentity.TileEntityMachineAnalysis;
import com.ollieread.technomagi.tileentity.TileEntityMachineAreaLight;
import com.ollieread.technomagi.tileentity.TileEntityMachineAssembler;
import com.ollieread.technomagi.tileentity.TileEntityMachineDisplacer;
import com.ollieread.technomagi.tileentity.TileEntityMachineEncourager;
import com.ollieread.technomagi.tileentity.TileEntityMachineFurnace;
import com.ollieread.technomagi.tileentity.TileEntityMachineInfuser;
import com.ollieread.technomagi.tileentity.TileEntityMachineInfuserCharger;
import com.ollieread.technomagi.tileentity.TileEntityMachineObservation;
import com.ollieread.technomagi.tileentity.TileEntityMachineProcessor;
import com.ollieread.technomagi.tileentity.TileEntityMachineReplicator;
import com.ollieread.technomagi.tileentity.TileEntityMachineTeleporter;
import com.ollieread.technomagi.tileentity.TileEntityPocketEnergy;
import com.ollieread.technomagi.tileentity.TileEntityPocketGrowth;
import com.ollieread.technomagi.tileentity.TileEntityPocketLight;
import com.ollieread.technomagi.tileentity.TileEntityPocketNanite;
import com.ollieread.technomagi.tileentity.TileEntityPrismaticPillar;
import com.ollieread.technomagi.tileentity.TileEntityReactiveCrafting;
import com.ollieread.technomagi.tileentity.TileEntityRegionControllerDamage;
import com.ollieread.technomagi.tileentity.TileEntityRegionControllerEffect;
import com.ollieread.technomagi.tileentity.TileEntityRegionControllerInteraction;
import com.ollieread.technomagi.tileentity.TileEntityRegionControllerPerception;
import com.ollieread.technomagi.tileentity.TileEntityRegionControllerPresence;
import com.ollieread.technomagi.tileentity.TileEntitySmartmetal;
import com.ollieread.technomagi.tileentity.TileEntityStorageFluid;
import com.ollieread.technomagi.tileentity.TileEntityStorageItems;

import cpw.mods.fml.common.registry.GameRegistry;

public class Blocks
{

    public static Block blockResource;
    public static Block blockMachine;
    public static Block blockLightAir;
    public static Block blockTeleporter;
    public static Block blockObservationChamber;
    public static Block blockEmptyFiller;
    public static Block blockHardlight;
    public static Block blockHardlightFence;
    public static Block blockHardlightGenerator;
    public static Block blockDisplacedAir;
    public static Block blockGenerator;
    public static Block blockReactiveCrafting;
    public static Block blockTank;
    public static Block blockStorage;
    public static Block blockFocusCharger;
    public static Block blockBattery;
    public static Block blockVoidBreach;
    public static BlockSmartmetal blockSmartmetal;
    public static Block blockSmartmetalTile;
    public static Block blockRegionController;
    public static Block blockPrismaticPillar;
    public static Block blockPocket;
    public static Block blockLight;
    public static Block blockDarkness;

    public static void init()
    {
        TechnoMagi.info("Initiating & registering blocks");

        blockResource = new BlockResource("resource").setHardness(5.0F).setResistance(10.0F);
        blockMachine = new BlockMachine("machine").setHardness(5.0F).setResistance(10.0F);
        blockLightAir = new BlockAirLight("lightAir");
        blockTeleporter = new BlockTeleporter("teleporter").setHardness(5.0F).setResistance(10.0F);
        blockObservationChamber = new BlockObservationChamber("observationChamber").setHardness(5.0F).setResistance(10.0F);
        blockEmptyFiller = new BlockFiller("emptyFiller").setHardness(5.0F).setResistance(10.0F);
        blockFocusCharger = new BlockMachineInfuserCharger("focusCharger").setHardness(5.0F).setResistance(10.0F);
        blockHardlight = new BlockHardlight("hardlight");
        blockHardlightFence = new BlockHardlightFence("hardlightFence");
        blockHardlightGenerator = new BlockHardlightGenerator("hardlightGenerator").setHardness(5.0F).setResistance(10.0F);
        blockDisplacedAir = new BlockDisplacedAir("displacedAir");
        blockGenerator = new BlockGenerator("generator").setHardness(5.0F).setResistance(10.0F);
        blockReactiveCrafting = new BlockReactiveCrafting("reactiveCrafting");
        blockTank = new BlockTank("tank").setHardness(5.0F).setResistance(10.0F);
        blockStorage = new BlockStorage("storage").setHardness(5.0F).setResistance(10.0F);
        blockBattery = new BlockBattery("battery").setHardness(5.0F).setResistance(10.0F);
        blockVoidBreach = new BlockVoidBreach("voidBreach");
        blockSmartmetal = new BlockSmartmetal("smartmetal");
        blockSmartmetalTile = new BlockSmartmetalTile("smartmetalTile");
        blockRegionController = new BlockRegionController("regionController");
        blockPrismaticPillar = new BlockPrismaticPillar("prismaticPillar");
        blockPocket = new BlockPocket("pocket");
        blockLight = new BlockLight("light");
        blockDarkness = new BlockDarkness("darkness");

        GameRegistry.registerBlock(blockResource, ItemBlockMulti.class, "resourceBlock");
        GameRegistry.registerBlock(blockMachine, ItemBlockMulti.class, "machine");
        GameRegistry.registerBlock(blockLightAir, "lightAir");
        GameRegistry.registerBlock(blockTeleporter, ItemBlockMulti.class, "teleporter");
        GameRegistry.registerBlock(blockObservationChamber, "observationChamber");
        GameRegistry.registerBlock(blockFocusCharger, "focusCharger");
        GameRegistry.registerBlock(blockEmptyFiller, "emptyFiller");
        GameRegistry.registerBlock(blockHardlight, "hardlight");
        GameRegistry.registerBlock(blockHardlightFence, "hardlightFence");
        GameRegistry.registerBlock(blockHardlightGenerator, "hardlightGenerator");
        GameRegistry.registerBlock(blockDisplacedAir, "displacedAir");
        GameRegistry.registerBlock(blockGenerator, ItemBlockMulti.class, "generator");
        GameRegistry.registerBlock(blockReactiveCrafting, "reactiveCrafting");
        GameRegistry.registerBlock(blockTank, ItemBlockMulti.class, "tank");
        GameRegistry.registerBlock(blockStorage, ItemBlockMulti.class, "storage");
        GameRegistry.registerBlock(blockBattery, "battery");
        GameRegistry.registerBlock(blockVoidBreach, "voidBreach");
        GameRegistry.registerBlock(blockSmartmetal, "smartmetal");
        GameRegistry.registerBlock(blockSmartmetalTile, "smartmetalOverlay");
        GameRegistry.registerBlock(blockRegionController, ItemBlockMulti.class, "regionController");
        GameRegistry.registerBlock(blockPrismaticPillar, "prismaticPillar");
        GameRegistry.registerBlock(blockPocket, ItemBlockMulti.class, "pocket");
        GameRegistry.registerBlock(blockLight, "light");
        GameRegistry.registerBlock(blockDarkness, "darkness");

        GameRegistry.registerTileEntity(TileEntityArchive.class, "tileEntityArchive");
        GameRegistry.registerTileEntity(TileEntityMachineReplicator.class, "tileEntityNaniteReplicator");
        GameRegistry.registerTileEntity(TileEntityAirLight.class, "tileEntityLightAir");
        GameRegistry.registerTileEntity(TileEntityFiller.class, "tileEntityEmptyFiller");
        GameRegistry.registerTileEntity(TileEntityAirDisplaced.class, "tileEntityDisplacedAir");
        GameRegistry.registerTileEntity(TileEntityGeneratorVoid.class, "tileEntityGeneratorVoid");
        GameRegistry.registerTileEntity(TileEntityGeneratorLight.class, "tileEntityGeneratorLight");
        GameRegistry.registerTileEntity(TileEntityGeneratorLife.class, "tileEntityGeneratorLife");
        GameRegistry.registerTileEntity(TileEntityConstruct.class, "tileEntityConstruct");
        GameRegistry.registerTileEntity(TileEntityReactiveCrafting.class, "tileEntityReactiveCrafting");
        GameRegistry.registerTileEntity(TileEntityStorageFluid.class, "tileEntityTank");
        GameRegistry.registerTileEntity(TileEntityStorageItems.class, "tileEntityStorage");
        GameRegistry.registerTileEntity(TileEntityBattery.class, "tileEntityBattery");
        GameRegistry.registerTileEntity(TileEntityAirVoidBreach.class, "tileEntityVoidBreach");
        GameRegistry.registerTileEntity(TileEntitySmartmetal.class, "tileEntitySmartmetal");
        GameRegistry.registerTileEntity(TileEntityPrismaticPillar.class, "tileEntityPrismaticPillar");
        // machines
        GameRegistry.registerTileEntity(TileEntityMachineAreaLight.class, "tileEntityAreaLight");
        GameRegistry.registerTileEntity(TileEntityMachineTeleporter.class, "tileEntityTeleporter");
        GameRegistry.registerTileEntity(TileEntityMachineObservation.class, "tileEntityObservationChamber");
        GameRegistry.registerTileEntity(TileEntityHardlightGenerator.class, "tileEntityHardlightGenerator");
        GameRegistry.registerTileEntity(TileEntityMachineAssembler.class, "tileEntityCrafting");
        GameRegistry.registerTileEntity(TileEntityMachineAnalysis.class, "tileEntityAnalysis");
        GameRegistry.registerTileEntity(TileEntityMachineDisplacer.class, "tileEntityDisplacer");
        GameRegistry.registerTileEntity(TileEntityMachineProcessor.class, "tileEntitySeparator");
        GameRegistry.registerTileEntity(TileEntityMachineFurnace.class, "tileEntityFurnace");
        GameRegistry.registerTileEntity(TileEntityMachineInfuser.class, "tileEntityFocuser");
        GameRegistry.registerTileEntity(TileEntityMachineEncourager.class, "tileEntityEncourager");
        GameRegistry.registerTileEntity(TileEntityMachineInfuserCharger.class, "tileEntityFocusCharger");
        // region controllers
        GameRegistry.registerTileEntity(TileEntityRegionControllerDamage.class, "tileEntityDamageFilter");
        GameRegistry.registerTileEntity(TileEntityRegionControllerEffect.class, "tileEntityEffectFilter");
        GameRegistry.registerTileEntity(TileEntityRegionControllerInteraction.class, "tileEntityInteractionFilter");
        GameRegistry.registerTileEntity(TileEntityRegionControllerPerception.class, "tileEntityPerceptionFilter");
        GameRegistry.registerTileEntity(TileEntityRegionControllerPresence.class, "tileEntityPresenceFilter");
        // pockets
        GameRegistry.registerTileEntity(TileEntityPocketEnergy.class, "tileEntityPocketEnergy");
        GameRegistry.registerTileEntity(TileEntityPocketGrowth.class, "tileEntityPocketGrowth");
        GameRegistry.registerTileEntity(TileEntityPocketLight.class, "tileEntityPocketLight");
        GameRegistry.registerTileEntity(TileEntityPocketNanite.class, "tileEntityPocketNanite");
    }
}
