package com.ollieread.technomagi.common.init;

import net.minecraft.block.Block;

import org.apache.logging.log4j.Level;

import com.ollieread.technomagi.TechnoMagi;
import com.ollieread.technomagi.block.BlockAnalysis;
import com.ollieread.technomagi.block.BlockArchive;
import com.ollieread.technomagi.block.BlockAreaLight;
import com.ollieread.technomagi.block.BlockBattery;
import com.ollieread.technomagi.block.BlockConstruct;
import com.ollieread.technomagi.block.BlockCrafting;
import com.ollieread.technomagi.block.BlockDisplacedAir;
import com.ollieread.technomagi.block.BlockDisplacer;
import com.ollieread.technomagi.block.BlockEmptyFiller;
import com.ollieread.technomagi.block.BlockEncourager;
import com.ollieread.technomagi.block.BlockFocusCharger;
import com.ollieread.technomagi.block.BlockFocuser;
import com.ollieread.technomagi.block.BlockFurnace;
import com.ollieread.technomagi.block.BlockGenerator;
import com.ollieread.technomagi.block.BlockHardlight;
import com.ollieread.technomagi.block.BlockHardlightFence;
import com.ollieread.technomagi.block.BlockHardlightGenerator;
import com.ollieread.technomagi.block.BlockLightAir;
import com.ollieread.technomagi.block.BlockNaniteReplicator;
import com.ollieread.technomagi.block.BlockObservationChamber;
import com.ollieread.technomagi.block.BlockPerceptionFilter;
import com.ollieread.technomagi.block.BlockPrismaticPillar;
import com.ollieread.technomagi.block.BlockReactiveCrafting;
import com.ollieread.technomagi.block.BlockResource;
import com.ollieread.technomagi.block.BlockSeparator;
import com.ollieread.technomagi.block.BlockSmartmetal;
import com.ollieread.technomagi.block.BlockSmartmetalTile;
import com.ollieread.technomagi.block.BlockStorage;
import com.ollieread.technomagi.block.BlockTank;
import com.ollieread.technomagi.block.BlockTeleporter;
import com.ollieread.technomagi.block.BlockVoidBreach;
import com.ollieread.technomagi.item.ItemBlockTM;
import com.ollieread.technomagi.tileentity.TileEntityAnalysis;
import com.ollieread.technomagi.tileentity.TileEntityArchive;
import com.ollieread.technomagi.tileentity.TileEntityAreaLight;
import com.ollieread.technomagi.tileentity.TileEntityBattery;
import com.ollieread.technomagi.tileentity.TileEntityConstruct;
import com.ollieread.technomagi.tileentity.TileEntityCrafting;
import com.ollieread.technomagi.tileentity.TileEntityDisplacedAir;
import com.ollieread.technomagi.tileentity.TileEntityDisplacer;
import com.ollieread.technomagi.tileentity.TileEntityEmptyFiller;
import com.ollieread.technomagi.tileentity.TileEntityEncourager;
import com.ollieread.technomagi.tileentity.TileEntityFocusCharger;
import com.ollieread.technomagi.tileentity.TileEntityFocuser;
import com.ollieread.technomagi.tileentity.TileEntityFurnace;
import com.ollieread.technomagi.tileentity.TileEntityGeneratorLife;
import com.ollieread.technomagi.tileentity.TileEntityGeneratorSolar;
import com.ollieread.technomagi.tileentity.TileEntityGeneratorVoid;
import com.ollieread.technomagi.tileentity.TileEntityHardlightGenerator;
import com.ollieread.technomagi.tileentity.TileEntityLightAir;
import com.ollieread.technomagi.tileentity.TileEntityNaniteReplicator;
import com.ollieread.technomagi.tileentity.TileEntityObservationChamber;
import com.ollieread.technomagi.tileentity.TileEntityPerceptionFilter;
import com.ollieread.technomagi.tileentity.TileEntityPrismaticPillar;
import com.ollieread.technomagi.tileentity.TileEntityReactiveCrafting;
import com.ollieread.technomagi.tileentity.TileEntitySeparator;
import com.ollieread.technomagi.tileentity.TileEntitySmartmetal;
import com.ollieread.technomagi.tileentity.TileEntityStorage;
import com.ollieread.technomagi.tileentity.TileEntityTank;
import com.ollieread.technomagi.tileentity.TileEntityTeleporter;
import com.ollieread.technomagi.tileentity.TileEntityVoidBreach;

import cpw.mods.fml.common.registry.GameRegistry;

public class Blocks
{

    public static Block blockResource;
    public static Block blockConstruct;
    public static Block blockArchive;
    public static Block blockNaniteReplicator;
    public static Block blockAreaLight;
    public static Block blockLightAir;
    public static Block blockTeleporter;
    public static Block blockObservationChamber;
    public static Block blockEmptyFiller;
    public static Block blockCrafting;
    public static Block blockAnalysis;
    public static Block blockHardlight;
    public static Block blockHardlightFence;
    public static Block blockHardlightGenerator;
    public static Block blockDisplacer;
    public static Block blockDisplacedAir;
    public static Block blockGenerator;
    public static Block blockReactiveCrafting;
    public static Block blockTank;
    public static Block blockStorage;
    public static Block blockSeparator;
    public static Block blockFurnace;
    public static Block blockFocuser;
    public static Block blockFocusCharger;
    public static Block blockEncourager;
    public static Block blockBattery;
    public static Block blockVoidBreach;
    public static BlockSmartmetal blockSmartmetal;
    public static Block blockSmartmetalTile;
    public static Block blockPerceptionFilter;
    public static Block blockPrismaticPillar;

    public static void init()
    {
        TechnoMagi.logger.log(Level.INFO, "Initiating & registering blocks");

        blockResource = new BlockResource("resource").setHardness(5.0F).setResistance(10.0F);
        blockConstruct = new BlockConstruct("construct").setHardness(5.0F).setResistance(10.0F);
        blockAreaLight = new BlockAreaLight("areaLight").setHardness(5.0F).setResistance(10.0F);
        blockLightAir = new BlockLightAir("lightAir");
        blockTeleporter = new BlockTeleporter("teleporter").setHardness(5.0F).setResistance(10.0F);
        blockObservationChamber = new BlockObservationChamber("observationChamber").setHardness(5.0F).setResistance(10.0F);
        blockArchive = new BlockArchive("archive").setHardness(5.0F).setResistance(10.0F);
        blockCrafting = new BlockCrafting("crafting").setHardness(5.0F).setResistance(10.0F);
        blockNaniteReplicator = new BlockNaniteReplicator("naniteReplicator").setHardness(5.0F).setResistance(10.0F);
        blockEmptyFiller = new BlockEmptyFiller("emptyFiller").setHardness(5.0F).setResistance(10.0F);
        blockAnalysis = new BlockAnalysis("analysis").setHardness(5.0F).setResistance(10.0F);
        blockSeparator = new BlockSeparator("separator").setHardness(5.0F).setResistance(10.0F);
        blockFurnace = new BlockFurnace("furnace").setHardness(5.0F).setResistance(10.0F);
        blockFocuser = new BlockFocuser("focuser").setHardness(5.0F).setResistance(10.0F);
        blockFocusCharger = new BlockFocusCharger("focusCharger").setHardness(5.0F).setResistance(10.0F);
        blockHardlight = new BlockHardlight("hardlight");
        blockHardlightFence = new BlockHardlightFence("hardlightFence");
        blockHardlightGenerator = new BlockHardlightGenerator("hardlightGenerator").setHardness(5.0F).setResistance(10.0F);
        blockDisplacer = new BlockDisplacer("displacer").setHardness(5.0F).setResistance(10.0F);
        blockDisplacedAir = new BlockDisplacedAir("displacedAir");
        blockGenerator = new BlockGenerator("generator").setHardness(5.0F).setResistance(10.0F);
        blockReactiveCrafting = new BlockReactiveCrafting("reactiveCrafting");
        blockTank = new BlockTank("tank").setHardness(5.0F).setResistance(10.0F);
        blockStorage = new BlockStorage("storage").setHardness(5.0F).setResistance(10.0F);
        blockEncourager = new BlockEncourager("encourager").setHardness(5.0F).setResistance(10.0F);
        blockBattery = new BlockBattery("battery").setHardness(5.0F).setResistance(10.0F);
        blockVoidBreach = new BlockVoidBreach("voidBreach");
        blockSmartmetal = new BlockSmartmetal("smartmetal");
        blockSmartmetalTile = new BlockSmartmetalTile("smartmetalTile");
        blockPerceptionFilter = new BlockPerceptionFilter("perceptionFilter");
        blockPrismaticPillar = new BlockPrismaticPillar("prismaticPillar");

        GameRegistry.registerBlock(blockResource, ItemBlockTM.class, "resourceBlock");
        GameRegistry.registerBlock(blockConstruct, "construct");
        GameRegistry.registerBlock(blockAreaLight, "areaLight");
        GameRegistry.registerBlock(blockLightAir, "lightAir");
        GameRegistry.registerBlock(blockTeleporter, ItemBlockTM.class, "teleporter");
        GameRegistry.registerBlock(blockObservationChamber, "observationChamber");
        GameRegistry.registerBlock(blockArchive, "archive");
        GameRegistry.registerBlock(blockCrafting, "crafting");
        GameRegistry.registerBlock(blockNaniteReplicator, "naniteReplicator");
        GameRegistry.registerBlock(blockAnalysis, "analysis");
        GameRegistry.registerBlock(blockSeparator, "separator");
        GameRegistry.registerBlock(blockFurnace, "furnace");
        GameRegistry.registerBlock(blockFocuser, "focuser");
        GameRegistry.registerBlock(blockFocusCharger, "focusCharger");
        GameRegistry.registerBlock(blockEmptyFiller, "emptyFiller");
        GameRegistry.registerBlock(blockHardlight, "hardlight");
        GameRegistry.registerBlock(blockHardlightFence, "hardlightFence");
        GameRegistry.registerBlock(blockHardlightGenerator, "hardlightGenerator");
        GameRegistry.registerBlock(blockDisplacer, "displacer");
        GameRegistry.registerBlock(blockDisplacedAir, "displacedAir");
        GameRegistry.registerBlock(blockGenerator, ItemBlockTM.class, "generator");
        GameRegistry.registerBlock(blockEncourager, "encourager");
        GameRegistry.registerBlock(blockReactiveCrafting, "reactiveCrafting");
        GameRegistry.registerBlock(blockTank, ItemBlockTM.class, "tank");
        GameRegistry.registerBlock(blockStorage, ItemBlockTM.class, "storage");
        GameRegistry.registerBlock(blockBattery, "battery");
        GameRegistry.registerBlock(blockVoidBreach, "voidBreach");
        GameRegistry.registerBlock(blockSmartmetal, "smartmetal");
        GameRegistry.registerBlock(blockSmartmetalTile, "smartmetalOverlay");
        GameRegistry.registerBlock(blockPerceptionFilter, "perceptionFilter");
        GameRegistry.registerBlock(blockPrismaticPillar, "prismaticPillar");

        GameRegistry.registerTileEntity(TileEntityArchive.class, "tileEntityArchive");
        GameRegistry.registerTileEntity(TileEntityNaniteReplicator.class, "tileEntityNaniteReplicator");
        GameRegistry.registerTileEntity(TileEntityLightAir.class, "tileEntityLightAir");
        GameRegistry.registerTileEntity(TileEntityAreaLight.class, "tileEntityAreaLight");
        GameRegistry.registerTileEntity(TileEntityTeleporter.class, "tileEntityTeleporter");
        GameRegistry.registerTileEntity(TileEntityObservationChamber.class, "tileEntityObservationChamber");
        GameRegistry.registerTileEntity(TileEntityEmptyFiller.class, "tileEntityEmptyFiller");
        GameRegistry.registerTileEntity(TileEntityHardlightGenerator.class, "tileEntityHardlightGenerator");
        GameRegistry.registerTileEntity(TileEntityCrafting.class, "tileEntityCrafting");
        GameRegistry.registerTileEntity(TileEntityAnalysis.class, "tileEntityAnalysis");
        GameRegistry.registerTileEntity(TileEntityDisplacer.class, "tileEntityDisplacer");
        GameRegistry.registerTileEntity(TileEntityDisplacedAir.class, "tileEntityDisplacedAir");
        GameRegistry.registerTileEntity(TileEntityGeneratorVoid.class, "tileEntityGeneratorVoid");
        GameRegistry.registerTileEntity(TileEntityGeneratorSolar.class, "tileEntityGeneratorLight");
        GameRegistry.registerTileEntity(TileEntityGeneratorLife.class, "tileEntityGeneratorLife");
        GameRegistry.registerTileEntity(TileEntityConstruct.class, "tileEntityConstruct");
        GameRegistry.registerTileEntity(TileEntityReactiveCrafting.class, "tileEntityReactiveCrafting");
        GameRegistry.registerTileEntity(TileEntityTank.class, "tileEntityTank");
        GameRegistry.registerTileEntity(TileEntityStorage.class, "tileEntityStorage");
        GameRegistry.registerTileEntity(TileEntitySeparator.class, "tileEntitySeparator");
        GameRegistry.registerTileEntity(TileEntityFurnace.class, "tileEntityFurnace");
        GameRegistry.registerTileEntity(TileEntityFocuser.class, "tileEntityFocuser");
        GameRegistry.registerTileEntity(TileEntityEncourager.class, "tileEntityEncourager");
        GameRegistry.registerTileEntity(TileEntityFocusCharger.class, "tileEntityFocusCharger");
        GameRegistry.registerTileEntity(TileEntityBattery.class, "tileEntityBattery");
        GameRegistry.registerTileEntity(TileEntityVoidBreach.class, "tileEntityVoidBreach");
        GameRegistry.registerTileEntity(TileEntitySmartmetal.class, "tileEntitySmartmetal");
        GameRegistry.registerTileEntity(TileEntityPerceptionFilter.class, "tileEntityPerceptionFilter");
        GameRegistry.registerTileEntity(TileEntityPrismaticPillar.class, "tileEntityPrismaticPillar");
    }
}
